# AD domain
ad_domain: fedora.solutions

# Where student user accounts live
students_ou: OU=Students,OU=HolyTrinityHS,OU=Clients,DC=fedora,DC=solutions

# Where grade security groups live
groups_ou: OU=Groups,OU=HolyTrinityHS,OU=Clients,DC=fedora,DC=solutions

# Grade â†’ Security Group mapping
grade_groups:
  "2026": SG_Grade-9
  "2027": SG_Grade-10
  "2028": SG_Grade-11
  "2029": SG_Grade-12

# Temporary password for new students
temp_password: "TempPassw0rd!"
